// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjPm0Mto8Bp9FvDAp0_BvwojCpMwFcmIU',
    appId: '1:771058194814:web:a56f46814380949f57fb2f',
    messagingSenderId: '771058194814',
    projectId: 'mohaf-9c8b0',
    authDomain: 'mohaf-9c8b0.firebaseapp.com',
    storageBucket: 'mohaf-9c8b0.firebasestorage.app',
    measurementId: 'G-X3JBW8P223',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV_TFgcJ5UpSW9qnvLolomcxz3bOs_ATE',
    appId: '1:771058194814:android:f380a89aac4eeb0b57fb2f',
    messagingSenderId: '771058194814',
    projectId: 'mohaf-9c8b0',
    storageBucket: 'mohaf-9c8b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRJB9wOO-mi4tByiZyMwTsUvuRoFRdhoY',
    appId: '1:771058194814:ios:ebb4d2d22f4c3eb757fb2f',
    messagingSenderId: '771058194814',
    projectId: 'mohaf-9c8b0',
    storageBucket: 'mohaf-9c8b0.firebasestorage.app',
    iosBundleId: 'com.example.choveen.choveenapp',
  );

}