name: choveen
description: AI-powered team collaboration platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2

  provider: ^6.1.1

  http: ^1.1.0
  dio: ^5.3.2

  shared_preferences: ^2.2.2

  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.10

  flutter_local_notifications: ^17.0.0

  json_annotation: ^4.8.1

  email_validator: ^2.1.17

  image_picker: ^1.0.4

  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/
